geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/read/', adminapp.OrderListView.as_view(), name='orders'),
    path('orders/update/<int:pk>/', adminapp.OrderUpdateView.as_view(), name='order_update'),
    path('orders/delete/<int:pk>/', adminapp.OrderDeleteView.as_view(), name='order_delete'),
    path('orders/read/<int:pk>/', adminapp.OrderDetailView.as_view(), name='order_read'),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.UserRegisterView.as_view(), name='register'),
    path('edit/<pk>/', authapp.UserEditView.as_view(), name='edit'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.IndexPageView.as_view(), name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.ContactPageView.as_view(), name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),
]

handler404 = mainapp.not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/adminapp/models.py
from django.db import models

# Create your models here.

geekshop/orderapp/models.py
from django.conf import settings
from django.db import models

from mainapp.models import Product


class Order(models.Model):
    FORMING = 'FM'
    SENT_TO_PROCESSING = 'STP'
    PROCESSED = 'PRD'
    PAID = 'PD'
    READY = 'RDY'
    DONE = 'DN'
    CANCELLED = 'CNC'

    ORDER_STATUSES = (
        (FORMING, 'формируется'),
        (SENT_TO_PROCESSING, 'отправлен в обработку'),
        (PROCESSED, 'обработан'),
        (PAID, 'оплачен'),
        (READY, 'готов к выдаче'),
        (DONE, 'выдан'),
        (CANCELLED, 'отменен'),
    )

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='пользователь')
    created = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='дата изменения')
    status = models.CharField(max_length=3, choices=ORDER_STATUSES, default=FORMING, verbose_name='статус заказа')
    is_active = models.BooleanField(db_index=True, default=True, verbose_name='активен')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'заказ'
        verbose_name_plural = 'заказы'

    def __str__(self):
        return f'Текущий заказ: #{self.id}'

    def get_total_quantity(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity, items)))

    def get_product_type_quantity(self):
        items = self.orderitems.select_related()
        return len(items)

    def get_total_cost(self):
        items = self.orderitems.select_related()
        return sum(list(map(lambda x: x.quantity * x.product.price, items)))

    def get_summary(self):
        items = self.orderitems.select_related()
        total_quantity = sum(list(map(lambda x: x.quantity, items)))
        total_cost = sum(list(map(lambda x: x.quantity * x.product.price, items)))
        return {
            'total_quantity': total_quantity,
            'total_cost': total_cost,
        }

    def delete(self):
        for item in self.orderitems.select_related():
            item.product.quantity += item.quantity
            item.product.save()

        self.is_active = False
        self.save()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='orderitems', on_delete=models.CASCADE, verbose_name='заказ')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='продукт')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество')

    def get_product_cost(self):
        return self.product.price * self.quantity

    @staticmethod
    def get_item(pk):
        return OrderItem.objects.filter(pk=pk).first()

geekshop/adminapp/forms.py
from django import forms

from authapp.forms import ShopUserEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from orderapp.models import Order, OrderItem


class ShopUserAdminEditForm(ShopUserEditForm):
    class Meta:
        model = ShopUser
        fields = '__all__'


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(label='скидка', required=False, min_value=0, max_value=90, initial=0)

    class Meta:
        model = ProductCategory
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super(ProductCategoryEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderEditForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class OrderItemEditForm(forms.ModelForm):
    class Meta:
        model = OrderItem
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

geekshop/adminapp/views.py
from django.contrib.auth.decorators import user_passes_test
from django.db import connection
from django.db.models import F
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from adminapp.forms import ShopUserAdminEditForm, ProductCategoryEditForm, ProductEditForm, OrderEditForm, \
    OrderItemEditForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from orderapp.models import Order, OrderItem


class UserCreateView(CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('adminapp:users')
    form_class = ShopUserAdminEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'пользователи / создание'
        return context


class UsersListView(ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'пользователи'
        return context


class UserUpdateView(UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('adminapp:users')
    form_class = ShopUserAdminEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'пользователи / редактирование'
        return context


class UserDeleteView(DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('adminapp:users')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'пользователи / удаление'
        return context


class ProductCategoryCreateView(CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:categories')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории / создание'
        return context


class ProductCategoryListView(ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории'
        return context


class ProductCategoryUpdateView(UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('adminapp:categories')
    form_class = ProductCategoryEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории / редактирование'
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set.update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(self.__class__, 'UPDATE', connection.queries)
        return super().form_valid(form)


class ProductCategoryDeleteView(DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('adminapp:categories')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'категории / удаление'
        return context


class ProductCreateView(CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('adminapp:products')
    form_class = ProductEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'продукты / создание'
        category_pk = self.kwargs.get('pk', None)
        if category_pk is not None:
            context['category'] = get_object_or_404(ProductCategory, pk=category_pk)
            context['form']['category'].initial = get_object_or_404(ProductCategory, pk=category_pk)
            return context

    def get_success_url(self):
        category_pk = self.object.category.pk
        return reverse_lazy('adminapp:products', kwargs={'pk': category_pk})


class ProductsListView(ListView):
    model = Product
    template_name = 'adminapp/products.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'продукты'
        category_pk = self.kwargs.get('pk', None)
        if category_pk is not None:
            context['category'] = get_object_or_404(ProductCategory, pk=category_pk)
            return context

    def get_queryset(self):
        queryset = super().get_queryset()
        category_pk = self.kwargs.get('pk', None)
        if category_pk is not None:
            queryset = Product.objects.filter(category_id=category_pk).select_related()
        return queryset


class ProductDetailView(DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'продукт / подробнее'
        return context


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    success_url = reverse_lazy('adminapp:products')
    form_class = ProductEditForm

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'продукты / редактирование'
        category_pk = self.object.category.pk
        if category_pk is not None:
            context['category'] = get_object_or_404(ProductCategory, pk=category_pk)
            return context

    def get_success_url(self):
        category_pk = self.object.category.pk
        return reverse_lazy('adminapp:products', kwargs={'pk': category_pk})


class ProductDeleteView(DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    success_url = reverse_lazy('adminapp:products')

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.object.is_active:
            self.object.is_active = False
        else:
            self.object.is_active = True
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'продукты / редактирование'
        category_pk = self.object.category.pk
        if category_pk is not None:
            context['category'] = get_object_or_404(ProductCategory, pk=category_pk)
            return context

    def get_success_url(self):
        category_pk = self.object.category.pk
        return reverse_lazy('adminapp:products', kwargs={'pk': category_pk})

geekshop/adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
    <div class="categories_list">
        <button class="new_category">
            <a href={% url 'adminapp:category_create' %}>
                новая категория
            </a>
        </button>

        {% for object in object_list %}
            <div class="category_record
        {% if not object.is_active %}
            not_active
        {% endif %}">
                <div class="category_name">
                    {{ object.name|title }}
                </div>
                <div class="category_actions">
                    <button>
                        <a href={% url 'adminapp:products' object.pk %}>
                            товары категории
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:category_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:category_delete' object.pk %}>
                            {% if object.is_active %}
                                удалить
                            {% else %}
                                восстановить
                            {% endif %}
                        </a>
                    </button>
                </div>
                <div class="category_desc">
                    {{ object.description }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="category_delete">
        Уверены, что хотите
        {% if object.is_active %}
            удалить
        {% else %}
            восстановить
        {% endif %}
        категорию
        {{ object.name }}?
        <form action="{% url 'adminapp:category_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            {% if object.is_active %}
                <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
                <input class="btn btn-danger" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'adminapp:categories' %}">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/order_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}


{% block content %}
    <div class="order_delete">
        Уверены, что хотите
        {% if object.is_active %}
            удалить
        {% else %}
            восстановить
        {% endif %}
        заказ №
        {{ object.pk }}
        пользователя {{ object.user.first_name|title }} {{ object.user.last_name|title }}?
        <form action="{% url 'adminapp:order_delete' object.pk %}"
              method="post">
            {% csrf_token %}
            {% if object.is_active %}
                <input class="btn btn-danger" type="submit" value="удалить">
            {% else %}
                <input class="btn btn-danger" type="submit" value="восстановить">
            {% endif %}
        </form>
        <button class="btn btn-success">
            <a href="{% url 'adminapp:orders' %}">
                Отмена
            </a>
        </button>
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/order_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load cache %}

{% block content %}
    <div class="order_form">
        <form action="" method="post">
            {% csrf_token %}
            <table class="table">
                {{ orderitems.management_form }}
                {% for form in orderitems.forms %}
                    {% if forloop.first %}
                        <thead>
                        <tr>
                            {% for field in form.visible_fields %}
                                <th class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                    {{ field.label|capfirst }}
                                </th>
                            {% endfor %}
                        </tr>
                        </thead>
                    {% endif %}
                    <tr class="formset_row">
                        {% for field in form.visible_fields %}
                            <td class="{% cycle 'td1' 'td2' 'td3' 'td4' %} order formset_td">
                                {% if forloop.first %}
                                    {% for hidden in form.hidden_fields %}
                                        {{ hidden }}
                                    {% endfor %}
                                {% endif %}
                                {{ field.errors.as_ul }}
                                {% if field.name != 'price' %}
                                    {% if field.name == 'product' %}
                                        {% cache 3600 orderitemform_product field.value %}
                                            {{ field }}
                                        {% endcache %}
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                {% else %}
                                    {% if field.value %}
                                        <span
                                                class="orderitems-{{ forloop.parentloop.counter0 }}-price">
                                            {{ field.value }}
                                        </span> руб
                                    {% endif %}
                                {% endif %}
                            </td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </form>
    </div>
    <button class="btn btn-default btn-round form-control last">
        <a href="{% url 'adminapp:order_delete' object.pk %}">
            удалить заказ
        </a>
    </button>
    <button class="btn btn-round form-control last">
        <a href="{% url 'adminapp:orders' %}">
            К списку заказов
        </a>
    </button>
{% endblock %}

geekshop/adminapp/templates/adminapp/orders.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="orders_list">
        <div class="paginator">
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">
                    <
                </a>
            {% endif %}
            <span class="current">
                        страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                    </span>
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">
                    >
                </a>
            {% endif %}
        </div>
        <div class="clearfix"></div>
        {% for object in object_list %}
            <div class="order_record
                    {% if not object.is_active %}
                        not_active
                    {% endif %}">
                <div class="order_information">
                    <p>
                        <strong>
                            Заказ №{{ object.pk }}<br>
                            Пользователь: {{ object.user.username|title }}<br>
                            Сумма: {{ object.get_total_cost }} руб.<br>
                            Статус: {{ object.get_status_display }}<br>
                            Изменен: {{ object.updated }}<br>
                        </strong>
                    </p>
                </div>
                <div class="order_actions">
                    <button>
                        <a href="{% url 'adminapp:order_update' object.pk %}">
                            редактировать заказ
                        </a>
                    </button>
                    {% if object.is_active %}
                        <button>
                            <a href="{% url 'adminapp:order_read' object.pk %}">
                                детали заказа
                            </a>
                        </button>
                    {% endif %}
                    <button>
                        <a href="{% url 'adminapp:order_delete' object.pk %}">
                            {% if object.is_active %}
                                удалить
                            {% else %}
                                восстановить
                            {% endif %}
                        </a>
                    </button>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="products_list">
        <button class="new_product">
            <a href={% url 'adminapp:product_create' category.pk %}>
                новый продукт
            </a>
        </button>

        {% for object in object_list %}
            {% if object.category.pk == category.pk %}
                <div class="product_record {% if not object.is_active %}not_active{% endif %}">
                    <img
                            src="{{ object.image|media_folder_products }}"
                            alt="{{ object.name }}">
                    <div class="product_name">
                        {{ object.name|title }}
                    </div>
                    <div class="product_actions">
                        <button>
                            <a href={% url 'adminapp:product_read' object.pk %}>
                                подробнее
                            </a>
                        </button>
                        <button>
                            <a href={% url 'adminapp:product_update' object.pk %}>
                                редактировать
                            </a>
                        </button>
                        <button>
                            <a href={% url 'adminapp:product_delete' object.pk %}>
                                {% if object.is_active %}
                                    удалить
                                {% else %}
                                    восстановить
                                {% endif %}
                            </a>
                        </button>
                    </div>
                    <div class="summary">
                        <b>цена</b>
                        <p>{{ object.price }} руб</p>
                        <b>количество</b>
                        <p>{{ object.quantity }}</p>
                    </div>
                    <div class="product_desc">
                        {{ object.short_desc }}
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

geekshop/adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="users_list">
        <button class="new_user">
            <a href={% url 'adminapp:user_create' %}>
                новый пользователь
            </a>
        </button>
        {% for object in object_list %}
            <div
                    class="user_record {% if not object.is_active %}not_active{% endif %}">
                <img src="{{ object.avatar|media_folder_users }}"
                     alt="{{ object.username }}">
                <div class="user_role">
                    {% if object.is_superuser %}
                        администратор
                    {% else %}
                        пользователь
                    {% endif %}
                    <button>
                        <a href={% url 'adminapp:user_update' object.pk %}>
                            редактировать
                        </a>
                    </button>
                    <button>
                        <a href={% url 'adminapp:user_delete' object.pk %}>
                            {% if object.is_active %}
                                удалить
                            {% else %}
                                восстановить
                            {% endif %}
                        </a>
                    </button>
                </div>
                <div class="user_name">
                    <p><strong>{{ object.username }}</strong></p>
                    <p>
                        {% if object.first_name %}
                            <b>{{ object.first_name|title }}</b>
                            {% if object.last_name %}
                                <p>{{ object.last_name|title }}</p>
                            {% endif %}
                        {% endif %}
                    </p>
                </div>
                <div class="user_age">
                    age:<br>
                    {{ object.age }} лет
                </div>
                <div class="user_email">
                    email:<br>
                    {{ object.email }}
                </div>
                <div class="user_lastlogin">
                    logged:<br>
                    {{ object.last_login }}
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}