geekshop/adminapp/urls.py
from django.urls import path
import adminapp.views as adminapp

app_name = 'adminapp'

urlpatterns = [
    path('users/create', adminapp.UserCreateView.as_view(), name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<pk>/', adminapp.UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<pk>/', adminapp.UserDeleteView.as_view(), name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.ProductCategoryListView.as_view(), name='categories'),
    path('categories/update/<pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.ProductCreateView.as_view(), name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.ProductsListView.as_view(), name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', adminapp.ProductDeleteView.as_view(), name='product_delete'),

    path('orders/read/', adminapp.OrderListView.as_view(), name='orders'),
    path('orders/update/<int:pk>/', adminapp.OrderUpdateView.as_view(), name='order_update'),
    path('orders/delete/<int:pk>/', adminapp.OrderDeleteView.as_view(), name='order_delete'),
    path('orders/read/<int:pk>/', adminapp.OrderDetailView.as_view(), name='order_read'),
]

geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.UserRegisterView.as_view(), name='register'),
    path('edit/<pk>/', authapp.UserEditView.as_view(), name='edit'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.BasketListView.as_view(), name='basket'),
    path('add/<pk>/', basketapp.basket_add, name='add'),
    path('remove/<pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.IndexPageView.as_view(), name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.ContactPageView.as_view(), name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),
]

handler404 = mainapp.not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product_page'),
]

geekshop/orderapp/urls.py
from django.urls import path
import orderapp.views as orderapp

app_name = 'orderapp'

urlpatterns = [
    path('', orderapp.OrderList.as_view(), name='orders_list'),
    path('create/', orderapp.OrderItemsCreate.as_view(), name='order_create'),
    path('read/<pk>/', orderapp.OrderRead.as_view(), name='order_read'),
    path('update/<pk>', orderapp.OrderItemsUpdate.as_view(), name='order_update'),
    path('delete/<pk>/', orderapp.OrderItemsDelete.as_view(), name='order_delete'),
    path('forming/<pk>/', orderapp.order_forming_complete, name='order_forming_complete'),
    path('processing/<pk>/', orderapp.order_processing_imitation, name='order_processing_imitation'),
    path('product/<pk>/price/', orderapp.get_product_price)
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')
    description = models.TextField(blank=True, verbose_name='описание')
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name='имя')
    image = models.ImageField(upload_to='products_images', blank=True, verbose_name='изображение')
    short_desc = models.CharField(max_length=128, verbose_name='краткое описание', blank=True)
    description = models.TextField(blank=True, verbose_name='описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество товара')
    is_active = models.BooleanField(db_index=True, default=True, verbose_name='активен')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/mainapp/views.py
import json
import os
import random

from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from mainapp.models import ProductCategory, Product

JSON_FILE_PATH = os.path.join(settings.BASE_DIR, 'mainapp/json')
with open(os.path.join(JSON_FILE_PATH, 'contact__locations.json'), 'r', encoding='utf-8') as f:
    contact_locations = json.load(f)


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_ordered_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products_list = get_products()
    try:
        return random.sample(list(products_list), 1)[0]
    except ValueError as e:
        print(f'error! {e}')
        dummy_cat = ProductCategory.objects.create(id=1, name='dummy')
        return Product.objects.create(pk=0, category_id=dummy_cat.id, name='dummy_product')


def get_same_products(hot_product):
    same_products = Product.objects.filter(category_id=hot_product.category_id).exclude(
        pk=hot_product.pk).select_related()[:3]
    return same_products


class IndexPageView(TemplateView):
    template_name = 'mainapp/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexPageView, self).get_context_data(**kwargs)
        context['title'] = 'главная'
        context['latest_products'] = get_products()[:3]
        return context


# @cache_page(3600)
def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = get_links_menu()

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все',
            }
            products_list = get_products_ordered_by_price()
        else:
            category = get_category(pk)
            products_list = get_products_in_category_ordered_by_price(pk)

        paginator = Paginator(products_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }
        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': "продукты",
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', content)


class ContactPageView(TemplateView):
    template_name = 'mainapp/contact.html'

    def get_context_data(self, **kwargs):
        context = super(ContactPageView, self).get_context_data(**kwargs)
        context['title'] = 'контакты'
        if settings.LOW_CACHE:
            key = 'contact_locations'
            locations = cache.get(key)
            if locations is None:
                context['locations'] = contact_locations
                cache.set(key, locations)
        else:
            context['locations'] = contact_locations
        return context


def not_found(request, exception):
    products = Product.objects.all()[:3]
    content = {
        'products': products
    }
    return render(request, 'mainapp/404.html', content)


def product(request, pk):
    product_item = get_product(pk)
    links_menu = get_links_menu()
    title = product_item.name
    content = {
        'title': title,
        'product': product_item,
        'links_menu': links_menu,
        'same_products': get_same_products(product_item),
    }

    return render(request, 'mainapp/product_page.html', content)

geekshop/mainapp/templates/mainapp/inc/inc_categories_menu.html
<ul class="links-menu">
    <li>
        <a href="{% url 'products:category' 0 %}">
            Все
        </a>
    </li>
    {% for item in links_menu %}
        <li>
            <a href="{% url 'products:category' item.pk %}">
                {{ item.name }}
            </a>
        </li>
    {% endfor %}
</ul>

geekshop/mainapp/templates/mainapp/inc/inc_main_menu.html
<a href="{% url 'main' %}" class="logo"></a>
<ul class="menu">
    <li>
        <a href="{% url 'main' %}"
           {% if request.resolver_match.url_name == 'main' %}class="active"{% endif %}>
            домой
        </a>
    </li>
    <li>
        <a href="{% url 'products:index' %}"
           {% if request.resolver_match.namespace == 'products' %}class="active"{% endif %}>
            продукты
        </a>
    </li>
    <li>
        <a href="{% url 'contact' %}"
           {% if request.resolver_match.url_name == 'contact' %}class="active"{% endif %}>
            контакты
        </a>
    </li>
    {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    {{ user.first_name|default:'Пользователь' }}
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a href="{% url 'auth:edit' user.pk %}">
                            Профиль
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'order:orders_list' %}">
                            Заказы
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    {% endif %}
    {% if user.is_superuser %}
        <li>
            <a href="{% url 'adminapp:users' %}">Админка</a>
        </li>
    {% endif %}
    <li>
        {% if user.is_authenticated %}
            <a href="{% url 'auth:logout' %}">Выйти</a>
        {% else %}
            <a href="{% url 'auth:login' %}">Войти</a>
        {% endif %}
    </li>
</ul>
<a href="#" class="search"></a>
<a href="{% url 'basket:basket' %}"
   class="basket">
    {% if basket %}
        <span>
            {{ basket.0.total_cost|floatformat:0 }} руб.
            ({{ basket.0.total_quantity }} шт.)
        </span>
        {% else %}
        <span>
            0 руб.
        </span>
    {% endif %}
</a>

geekshop/mainapp/templates/mainapp/inc/inc_products_categories.html
{% load static %}
<div class="details-products">
    <div class="details-slider">
        <div class="slider-product">
            <img src="{% static "img/slider1.jpg" %}">
        </div>
        <div class="slider-control">
            <div class="block">
                <a href="#"><img src="{% static "img/controll.jpg" %}" alt="">
                    <div class="text"></div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="{% static "img/controll1.jpg" %}" alt="">
                    <div class="text"></div>
                </a>
            </div>
            <div class="block">
                <a href="#"><img src="{% static "img/controll2.jpg" %}" alt="">
                    <div class="text"></div>
                </a>
            </div>
        </div>
    </div>

    <div class="description">
        <h3 class="big-bold">Отличный стул</h3>
        <h3 class="red">горячее предложение</h3>
        <p class="price"> 2585.9 <span>руб</span></p>
        <a href="#" class="red-button">
            заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
            <p>Расположитесь комфортно.</p>
            <p>Отличное качество материалов
                позволит вам это.</p>
            <p>Различные цвета</p>
            <p>высочайший уровень
                эргономики и прочность.</p>
        </div>
    </div>
</div>