geekshop/authapp/urls.py
from django.urls import path
import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.UserRegisterView.as_view(), name='register'),
    path('edit/<pk>/', authapp.UserEditView.as_view(), name='edit'),
    path('verify/<email>/<activation_key>', authapp.verify, name='verify'),
]

geekshop/basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.BasketListView.as_view(), name='basket'),
    path('add/<pk>/', basketapp.basket_add, name='add'),
    path('remove/<pk>/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.edit, name='edit'),
]

geekshop/geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

import mainapp.views as mainapp

urlpatterns = [
    path('', mainapp.IndexPageView.as_view(), name='main'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('contact/', mainapp.ContactPageView.as_view(), name='contact'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('orderapp.urls', namespace='order')),
]

handler404 = mainapp.not_found

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/mainapp/urls.py
from django.urls import path
import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    path('category/<int:pk>/', mainapp.products, name='category'),
    path('category/<int:pk>/page/<int:page>', mainapp.products, name='page'),
    path('product/<int:pk>/', mainapp.product, name='product_page'),
]

geekshop/mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True, verbose_name='имя')
    description = models.TextField(blank=True, verbose_name='описание')
    is_active = models.BooleanField(db_index=True, verbose_name='активна', default=True)

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=128, verbose_name='имя')
    image = models.ImageField(upload_to='products_images', blank=True, verbose_name='изображение')
    short_desc = models.CharField(max_length=128, verbose_name='краткое описание', blank=True)
    description = models.TextField(blank=True, verbose_name='описание')
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0, verbose_name='цена')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='количество товара')
    is_active = models.BooleanField(db_index=True, default=True, verbose_name='активен')

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

geekshop/mainapp/views.py
import json
import os
import random

from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView

from mainapp.models import ProductCategory, Product

JSON_FILE_PATH = os.path.join(settings.BASE_DIR, 'mainapp/json')
with open(os.path.join(JSON_FILE_PATH, 'contact__locations.json'), 'r', encoding='utf-8') as f:
    contact_locations = json.load(f)


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_ordered_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by(
                'price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def get_hot_product():
    products_list = get_products()
    try:
        return random.sample(list(products_list), 1)[0]
    except ValueError as e:
        print(f'error! {e}')
        dummy_cat = ProductCategory.objects.create(id=1, name='dummy')
        return Product.objects.create(pk=0, category_id=dummy_cat.id, name='dummy_product')


def get_same_products(hot_product):
    same_products = Product.objects.filter(category_id=hot_product.category_id).exclude(
        pk=hot_product.pk).select_related()[:3]
    return same_products


class IndexPageView(TemplateView):
    template_name = 'mainapp/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexPageView, self).get_context_data(**kwargs)
        context['title'] = 'главная'
        context['latest_products'] = get_products()[:3]
        return context


# @cache_page(3600)
def products(request, pk=None, page=1):
    title = 'продукты'
    links_menu = get_links_menu()

    if pk is not None:
        if pk == 0:
            category = {
                'pk': 0,
                'name': 'все',
            }
            products_list = get_products_ordered_by_price()
        else:
            category = get_category(pk)
            products_list = get_products_in_category_ordered_by_price(pk)

        paginator = Paginator(products_list, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
        }
        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': "продукты",
        'links_menu': links_menu,
        'hot_product': hot_product,
        'same_products': same_products,
    }
    return render(request, 'mainapp/products.html', content)


class ContactPageView(TemplateView):
    template_name = 'mainapp/contact.html'

    def get_context_data(self, **kwargs):
        context = super(ContactPageView, self).get_context_data(**kwargs)
        context['title'] = 'контакты'
        if settings.LOW_CACHE:
            key = 'contact_locations'
            locations = cache.get(key)
            if locations is None:
                context['locations'] = contact_locations
                cache.set(key, locations)
        else:
            context['locations'] = contact_locations
        return context


def not_found(request, exception):
    products = Product.objects.all()[:3]
    content = {
        'products': products
    }
    return render(request, 'mainapp/404.html', content)


def product(request, pk):
    product_item = get_product(pk)
    links_menu = get_links_menu()
    title = product_item.name
    content = {
        'title': title,
        'product': product_item,
        'links_menu': links_menu,
        'same_products': get_same_products(product_item),
    }

    return render(request, 'mainapp/product_page.html', content)

geekshop/mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
        <link rel="stylesheet" href="{% static "fonts/font-awesome/css/font-awesome.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">
    {% endblock %}
    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>
<body>
<div class="container">
    {% block menu %}
        <div class="hero-white">
            <div class="header clearfix">
                {% include 'mainapp/inc/inc_main_menu.html' %}
            </div>
        </div>
    {% endblock %}
    <div class="content">
        {% block content %}

        {% endblock %}
    </div>
</div>

<div class="clr"></div>

{% block footer %}
    <div class="footer">
        <div class="clearfix">
            <div class="text-footer">
                <h3>контакты</h3>
            </div>
            <div class="text-footer">
                <h3>полезная информация</h3>
            </div>
            <div class="text-footer clearfix">
                <h3>Оставайтесь на связи</h3>
                <p>Подписаться на новости и рассылки</p>
                <form>
                    <input type="email" name="email" placeholder="ваш email">
                    <a href="#"><i class="fa fa-paper-plane fa-2x" aria-hidden="true"></i></a>
                </form>
            </div>
        </div>
        <p class="small">&copy; GB {% now 'Y' %}</p>
        <div class="social">
            <a href="#" class="social1"></a>
            <a href="#" class="social2"></a>
            <a href="#" class="social3"></a>
            <a href="#" class="social4"></a>
        </div>
        <p class="small">Положения &amp; Условия / Конфиденциальность &amp; Cookies</p>
    </div>
{% endblock %}

</body>
</html>

geekshop/mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% block menu %}
    <div class="hero">
        <div class="header clearfix">
            {% include "mainapp/inc/inc_main_menu.html" %}
        </div>
        <h1>наши контакты</h1>
    </div>
{% endblock %}
{% block content %}
    <div class="location">
        {% for location in locations %}
            <div class="location-1">
                <i class="fa fa-map-marker fa-5x"></i>
                <h4>{{ location.city }}</h4>
                <div class="contacts">
                    <h5>Телефон</h5>
                    <p>{{ location.phone }}</p>
                </div>
                <div class="contacts">
                    <h5>Email</h5>
                    <p>{{ location.email }}</p>
                </div>
                <div class="contacts">
                    <h5>Адрес</h5>
                    <p>{{ location.address }}</p>
                </div>
            </div>
        {% endfor %}
        </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load custom_tags %}

{% block menu %}
    <div class="slider">
        <div class="header clearfix">
            {% include "mainapp/inc/inc_main_menu.html" %}
        </div>
        <div class="text-slider">
            <h3 class="green">тенденции</h3>
            <h3 class="big"> удобные стулья</h3>
            <p>Новый уровень комфорта. Отличные характеристики.</p>
            <a href="#" class="button-order">заказать <img src="{% static "img/arrow.png" %}" alt=""></a>
        </div>
        <div class="navi">
            <a href="#"></a><a href="#"></a><a href="#"></a>
        </div>
    </div>
{% endblock %}

{% block content %}
    <div class="featured">
        <div class="featured-menu">
            <a class="active" href="#">Популярные</a><a href="#">Новинки</a>
        </div>
        <a class="explore" href="#">показать все <img src="{% static "img/arrow.png" %}" alt=""></a>
        <div class="clearfix">
        </div>
        <div class="tab-content">
            {% for product in latest_products %}
                <div class="block">
                    <a href="{% url 'products:product_page' product.pk %}"><img
                            src="{{ product.image|media_folder_products }}" alt="{{ product.short_desc }}">
                        <div class="text">
                            <img src="{% static "img/icon-hover.png" %}" alt="img">
                            <h3>Категория: {{ product.category.name }}</h3>
                            <h4>Название: {{ product.name }}</h4>
                            <p>Описание: {{ product.description }}</p>
                            <p>Цена: {{ product.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/product_page.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load custom_tags %}
{% load cache %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/inc/inc_categories_menu.html' %}
        </div>
        {% cache 3600 product_detailed_info %}
            <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ product.image|media_folder_products }}" alt="">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{{ product.image|media_folder_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ product.image|media_folder_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ product.image|media_folder_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ product.name|title }}</h3>
                <h3 class="red">{{ product.category.name }}</h3>
                <p class="price"> {{ product.price|floatformat:0 }} <span>руб</span></p>
                <a href="{% url 'basket:add' product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ product.description }}
                </div>
            </div>
        {% endcache %}
        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static "img/arrow.png" %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for product in same_products %}
                    <div class="block">
                        <a href="{% url 'products:product_page' product.pk %}"><img
                                src="{{ product.image|media_folder_products }}" alt="{{ product.short_desc }}">
                            <div class="text">
                                <img src="/static/img/icon-hover.png" alt="img">
                                <h3>Категория: {{ product.category.name }}</h3>
                                <h4>Название: {{ product.name }}</h4>
                                <p>Описание: {{ product.description }}</p>
                                <p>Цена: {{ product.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
        </div>

        <div class="clr"></div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/inc/inc_categories_menu.html' %}
        </div>

        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ hot_product.image|media_folder_products }}" alt="">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|media_folder_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|media_folder_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|media_folder_products }}" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name|title }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price|floatformat:0 }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    {{ hot_product.description }}
                </div>
            </div>

            <div class="related">
                <div class="title clearfix">
                    <h2>Похожие продукты</h2>
                    <a class="explore" href="#">показать все <img src="{% static "img/arrow.png" %}" alt=""></a>
                </div>
                <div class="related-products clearfix">
                    {% for product in same_products %}
                        <div class="block">
                            <a href="{% url 'products:product_page' product.pk %}"><img
                                    src="{{ product.image|media_folder_products }}" alt="{{ product.short_desc }}">
                                <div class="text">
                                    <img src="/static/img/icon-hover.png" alt="img">
                                    <h3>Категория: {{ product.category.name }}</h3>
                                    <h4>Название: {{ product.name }}</h4>
                                    <p>Описание: {{ product.description }}</p>
                                    <p>Цена: {{ product.price }}</p>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="clr"></div>
    </div>
{% endblock %}

geekshop/mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}
{% load custom_tags %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/inc/inc_categories_menu.html' %}
        </div>

        <div class="products_list">
            <div class="title clearfix">
                <h2>Категория: "{{ category.name|title }}"</h2>
                <div class="paginator">
                    {% if products.has_previous %}
                        <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                            <
                        </a>
                    {% endif %}
                    <span class="current">
                        страница {{ products.number }} из {{ products.paginator.num_pages }}
                    </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">
                            >
                        </a>
                    {% endif %}
                </div>
            </div>
            <div class="category-products clearfix">

                {% for product in products %}
                    <div class="block">
                        <a href="{% url 'products:product_page' product.pk %}">
                            <img src="{{ product.image|media_folder_products }}" alt="product">
                            <div class="text">
                                <img src="{% static 'img/icon-hover.png' %}" alt="hover">
                                <h4>{{ product.name }}</h4>
                                <p>{{ product.description }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}

            </div>
        </div>
    </div>

    <div class="clr"></div>

{% endblock %}